[project]
name = "ShatterStack"
version = "0.1.0"
description = "A game where you have to place shapes in lines to get points!"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
 "arcade==3.2.0",
 "pypresence>=4.3.0",
]
